name: disney
description: A new Flutter project.

version: 0.0.1+1

environment:
    sdk: '>=2.19.4 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    http: ^1.1.0
    provider: ^6.0.5
    english_words: ^4.0.0
    image_picker: ^1.0.4
    image_compare_2: ^1.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
